@extends('admin.layout')
@section('title', 'Overview')
@section('content')
<div class="page-heading"><div><span class="eyebrow">WORKSPACE OVERVIEW</span><h1>Selamat datang, {{ explode(' ', (auth()->user()?->name ?? 'Admin'))[0] }} <span class="wave">✦</span></h1><p>Ringkasan katalog, booking preview, dan pesan pelanggan Anda.</p></div><span class="date-label">{{ now()->translatedFormat('d F Y') }}</span></div>
<div class="stats-grid">@foreach($counts as $label=>$count)<article class="stat-card"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon">{{ ['◇','◎','▤','✉'][$loop->index] }}</span></div><strong>{{ number_format($count) }}</strong><small>{{ ['Siap ditampilkan di website','Pilihan tujuan perjalanan','Total permintaan preview','Menunggu tindak lanjut'][$loop->index] }}</small></article>@endforeach</div>
<div class="overview-grid"><section class="panel"><div class="panel-heading"><div><h2>Booking terbaru</h2><p>Aktivitas permintaan perjalanan</p></div><a href="{{ route('admin.resources.index','bookings') }}">Lihat semua ↗</a></div><div class="table-wrap"><table><thead><tr><th>Pelanggan</th><th>Keberangkatan</th><th>Status</th></tr></thead><tbody>@forelse($bookings as $booking)<tr><td><a class="record-link" href="{{ route('admin.resources.show',['bookings',$booking->getKey()]) }}">{{ $booking->lead_name }}</a><small>{{ $booking->reference_code }}</small></td><td>{{ $booking->departure_date?->format('d M Y') }}</td><td><span class="badge">{{ $booking->preview_status }}</span></td></tr>@empty<tr><td colspan="3"><div class="empty-state">Belum ada booking preview.<small>Permintaan dari website akan tampil di sini.</small></div></td></tr>@endforelse</tbody></table></div><div class="panel-note">Booking merupakan preview perjalanan, bukan transaksi pembayaran.</div></section><section class="panel"><div class="panel-heading"><div><h2>Pesan masuk</h2><p>Percakapan dengan pelanggan</p></div><a href="{{ route('admin.resources.index','contacts') }}">↗</a></div>@forelse($contacts as $contact)<a class="message-row" href="{{ route('admin.resources.show',['contacts',$contact->getKey()]) }}"><span class="message-avatar">{{ strtoupper(substr($contact->full_name,0,1)) }}</span><div><strong>{{ $contact->full_name }}</strong><p>{{ $contact->topic }}</p><small>{{ $contact->created_at?->diffForHumans() }}</small></div><span class="message-status {{ $contact->status==='new'?'unread':'' }}"></span></a>@empty<div class="empty-state">Inbox masih kosong.<small>Pesan kontak pelanggan akan tampil di sini.</small></div>@endforelse</section></div>
<section class="quick-banner"><div><span class="eyebrow">MAKE YOUR NEXT MOVE</span><h2>Pengalaman berikutnya dimulai di sini.</h2><p>Perbarui katalog dan bantu pelanggan menemukan perjalanan mereka.</p></div><a class="button primary" href="{{ route('admin.resources.create','packages') }}">+ Tambah paket perjalanan</a></section>
@endsection

