<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'Overview') · Travel CMS</title><link rel="stylesheet" href="{{ asset('css/admin.css') }}"><script src="{{ asset('js/admin.js') }}" defer></script></head><body>
<a href="#main-content" class="skip-link">Lewati navigasi</a><div class="shell"><div class="sidebar-backdrop" data-close-sidebar></div><aside class="sidebar" id="admin-sidebar" aria-label="Navigasi admin"><button class="mobile-close" aria-label="Tutup navigasi">×</button><a class="brand" href="{{ route('admin.dashboard') }}"><span class="brand-mark">↗</span><span>Travel<span class="brand-light">desk</span><small>CONTENT MANAGEMENT</small></span></a><div class="workspace"><span class="workspace-icon">T</span><div>Travel & Experiences<small>Admin workspace</small></div><span class="workspace-dot"></span></div>
<nav><p class="nav-group">WORKSPACE</p><a class="nav-link {{ request()->routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}"><span class="nav-icon">▦</span>Overview</a>
@foreach(app(\App\Services\AdminResourceRegistry::class)->all() as $slug => $module)
@if($loop->first || $module['group'] !== $previousGroup)<p class="nav-group">{{ strtoupper($module['group']) }}</p>@endif
<a class="nav-link {{ request()->route('resource') === $slug ? 'active' : '' }}" href="{{ route('admin.resources.index', $slug) }}"><span class="nav-icon">{{ ['Travel Catalog'=>'◇','Content'=>'▤','Operations'=>'◷'][$module['group']] }}</span>{{ $module['label'] }}</a>@php($previousGroup = $module['group'])
@endforeach</nav><div class="sidebar-footer"><span class="avatar">{{ strtoupper(substr((auth()->user()?->name ?? 'Admin'),0,1)) }}</span><div>{{ (auth()->user()?->name ?? 'Admin') }}<small>{{ auth()->check() ? 'Administrator' : 'Mode tanpa login' }}</small></div>@if(auth()->check())<form action="{{ route('admin.logout') }}" method="post">@csrf<button class="logout" title="Keluar" aria-label="Keluar">↪</button></form>@endif</div></aside>
<div class="main"><header class="topbar"><button class="mobile-menu" aria-label="Buka navigasi" aria-expanded="false" aria-controls="admin-sidebar">☰</button><div class="breadcrumb">Workspace <span>/</span> <strong>@yield('title', 'Overview')</strong></div><div class="topbar-right"><span class="environment"><i></i> Admin CMS</span><a href="{{ route('home') }}" target="_blank" rel="noopener" class="site-link">Lihat website ↗</a></div></header><main class="content" id="main-content">@if(session('success'))<div class="notice success" role="status">✓ {{ session('success') }}</div>@endif @if(session('error'))<div class="notice error" role="alert">{{ session('error') }}</div>@endif @yield('content')<footer class="page-footer">Traveldesk CMS <span>Kelola perjalanan. Ciptakan pengalaman.</span></footer></main></div></div>
<dialog id="delete-dialog"><form method="dialog"><div class="dialog-icon">!</div><h2>Hapus data ini?</h2><p>Data yang dihapus tidak dapat dikembalikan. Data yang masih memiliki relasi akan tetap dilindungi.</p><div class="dialog-actions"><button class="button secondary" value="cancel">Batal</button><button class="button danger" value="confirm">Ya, hapus data</button></div></form></dialog>
</body></html>



